{% include 'misc/header.py' %}
notifications:
  email: false

sudo: false

language: python

cache: pip

python:
  - 2.7
  - 3.6

matrix:
  fast_finish: true

before_install:
  - travis_retry pip install --upgrade pip setuptools
  - travis_retry pip install coveralls

install:
  - travis_retry pip install -e .[tests]

script:
  - py.test {{ cookiecutter.package_name }} tests

after_success:
  - coveralls
